package com.example.diego.catalogo.banco;

import android.content.ContentValues;

import com.example.suporte.catalogo.R;

import java.util.ArrayList;

/**
 * Created by dblac on 24/07/2017.
 */

public class ScriptSQL {

    ArrayList<Produtos> produtos = new ArrayList<Produtos>();

    public static String createProdutos(){
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append("CREATE TABLE PRODUTOS ( ");
        stringBuilder.append("ID INTEGER PRIMARY KEY AUTOINCREMENT, ");
        stringBuilder.append("CODIGO INTEGER NOT NULL UNIQUE,");
        stringBuilder.append("DESCRICAO VARCHAR (40) NOT NULL, ");
        stringBuilder.append("DEPARTAMENTO INTEGER NOT NULL, ");
        stringBuilder.append("CAMINHO VARCHAR (50) NOT NULL, ");
        stringBuilder.append("PADARIA CHAR (1) CHECK (PADARIA IN ('S', 'N') ), ");
        stringBuilder.append("MERCADINHO CHAR (1) CHECK (MERCADINHO IN ('S', 'N') ), ");
        stringBuilder.append("RESTAURANTE CHAR (1) CHECK (RESTAURANTE IN ('S', 'N') ), ");
        stringBuilder.append("CLINICAS CHAR (1) CHECK (CLINICAS IN ('S', 'N') ) ");
        stringBuilder.append("); ");

        return stringBuilder.toString();
    }

    public static String inserirFoto(){

        /*Produtos p = new Produtos();
        p.setCodigo();
        p.setDescricao();
        p.setDepartamento();
        p.setCaminho();
        p.setPadaria();
        p.setMercadinho();
        p.setRestaurante();
        p.setClinica();
        p.setHoteis('N');*/

        StringBuilder stringBuilder = new StringBuilder();

        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4952, 'ALFINETE PARA MAPA 6MM BOLA BRW', 103, 'brw_alfinete_6mm', 'N', 'N', 'N', 'N'); ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4951, 'ALFINETE PARA MAPA 8MM BOLA BRW', 103, 'brw_alfinete_8mm', 'N', 'N', 'N', 'N'); ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4953, 'APAGADOR P/ QUADRO BRANCO BRW MAGNE AZUL', 103, 'brw_apagador_quadro_branco', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2212, 'APLICADOR MANUAL PARA FITA AZUL BRW', 103, 'brw_aplicador_manual_fita_azul', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2213, 'APLICADOR MANUAL PARA FITA VERMELHO BRW', 103, 'brw_aplicador_manual_fita_vermelho', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2104, 'APONTADOR ESC REDONDO  BRW', 103, 'brw_apontador_escolar_redondo', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (1166, 'ARMACAO BRALIMPIA 40CM PROFI', 102, 'brlimpia_armacao_profissional', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4653, 'ARMACAO BRALIMPIA 45CM PROFI', 102, 'brlimpia_armacao_profissional', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (1168, 'ARMACAO BRALIMPIA 60CM PROFI', 102, 'brlimpia_armacao_profissional', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4464, 'BALDE 10L SEKITO ZIG ZAG BETTANIN', 102, 'bettanin_balde_10l_sekito', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4463, 'BALDE 14L NOVIÇA ZIG ZAG BETTANIN', 102, 'bettanin_balde_14l_zig_zag', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2991, 'BALDE 4L C ALCA BRALIMPIA VERMELHO', 102, 'bralimpia_balde_4l_com_alca', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (836, 'BALDE ESPREMEDOR BRALIMPIA DOBLO AMARELO', 102, 'bralimpia_balde_espremedor_doblo', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (837, 'BALDE ESPREMEDOR BRALIMPIA DOBLO AZUL', 102, 'bralimpia_balde_espremedor_doblo', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (838, 'BALDE ESPREMEDOR BRALIMPIA DOBLO VERDE', 102, 'bralimpia_balde_espremedor_doblo', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (839, 'BALDE ESPREMEDOR BRALIMPIA DOBLO VERMELH', 102, 'bralimpia_balde_espremedor_doblo', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2040, 'BALDE ESPREMEDOR MOPINHO BRALIMPIA AMARE', 102, 'bralimpia_balde_espremedor_mopinho', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2039, 'BALDE ESPREMEDOR MOPINHO BRALIMPIA AZUL', 102, 'bralimpia_balde_espremedor_mopinho', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2998, 'BALDE ESPREMEDOR MOPINHO BRALIMPIA VERDE', 102, 'bralimpia_balde_espremedor_mopinho', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2031, 'BALDE ESPREMEDOR MOPINHO BRALIMPIA VERME', 102, 'bralimpia_balde_espremedor_mopinho', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2967, 'BASE SELADORA INNOVATION AUDAX 5LT', 102, 'audax_base_seladora_innovation', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2744, 'BASTAO COLA QUENTE FINA BRW', 103, 'brw_bastao_cola_quente_fina', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2745, 'BASTAO COLA QUENTE GROSSA BRW', 103, 'brw_bastao_cola_quente_grossa', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2114, 'BINDER CLIP BRW 25MM', 103, 'brw_binder_clip', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2111, 'BINDER CLIP BRW 32MM', 103, 'brw_binder_clip', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4954, 'BLOCO DE ANOT 38X51MM AMARELO 4UND BRW', 103, 'brw_bloco_anotacao_38x51_amarelo', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4956, 'BLOCO DE ANOT 38X51MM LARANJA 4UN BRW', 103, 'brw_bloco_anotacao_38x51_laranja', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4964, 'BLOCO DE ANOT 76X76MM CUBO 400 FLS BRW', 103, 'brw_bloco_anotacao_76x76_colorido', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4955, 'BLOCO DE ANOTACOES 38X51MM COLORIDO BRW', 103, 'brw_bloco_anotacao_38x51_colorido', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4957, 'BLOCO DE ANOTACOES 38X51MM ROSA 4UN BRW', 103, 'brw_bloco_anotacao_38x51_rosa', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4958, 'BLOCO DE ANOTACOES 38X51MM VERDE 4UN BRW', 103, 'brw_bloco_anotacao_38x51_verde', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4959, 'BLOCO DE ANOTACOES 76X102MM AMARELO BRW', 103, 'brw_bloco_anotacao_76x102_amarelo', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4960, 'BLOCO DE ANOTACOES 76X102MM LARANJA BRW', 103, 'brw_bloco_anotacao_76x102_laranja', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4961, 'BLOCO DE ANOTACOES 76X102MM ROSA BRW', 103, 'brw_bloco_anotacao_76x102_rosa', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4962, 'BLOCO DE ANOTACOES 76X102MM VERDE BRW', 103, 'brw_bloco_anotacao_76x102_verde', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4963, 'BLOCO DE ANOTACOES 76X76MM AMARELO BRW', 103, 'brw_bloco_anotacao_76x76_amarelo', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4965, 'BLOCO DE ANOTACOES 76X76MM LARANJA BRW', 103, 'brw_bloco_anotacao_76x76_laranja', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4966, 'BLOCO DE ANOTACOES 76X76MM ROSA BRW', 103, 'brw_bloco_anotacao_76x76_rosa', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4967, 'BLOCO DE ANOTACOES 76X76MM VERDE BRW', 103, 'brw_bloco_anotacao_76x76_verde', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2109, 'BORRACHA BRANCA BRW COM CAPA PEQUENA', 103, 'brw_borracha_com_capa', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (823, 'CABO BRALIMPIA 22MMX1.4MT FOSCO', 102, 'bralimpia_cabo_fosco', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5777, 'CAIXA ARQUIVO COMERCIAL POLYCART AZUL', 103, 'polycart_caixa_arquivo_morto', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5778, 'CAIXA ARQUIVO COMERCIAL POLYCART CINZA', 103, 'polycart_caixa_arquivo_morto', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5775, 'CAIXA ARQUIVO COMERCIAL POLYCART PRETO', 103, 'polycart_caixa_arquivo_morto', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5774, 'CAIXA ARQUIVO COMERCIAL POLYCART VERDE', 103, 'polycart_caixa_arquivo_morto', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5776, 'CAIXA ARQUIVO COMERCIAL POLYCART VERME', 103, 'polycart_caixa_arquivo_morto', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3395, 'CAIXA CORRESPOND DUPLA WALEU CRISTAL', 103, 'waleu_caixa_correspondencia_dupla_cristal', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3396, 'CAIXA CORRESPOND DUPLA WALEU FUME', 103, 'waleu_caixa_correspondencia_dupla_fume', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4350, 'CAIXA CORRESPOND SIMPLES WALEU CRISTAL', 103, 'waleu_caixa_correspondencia_simples_cristal', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3397, 'CAIXA CORRESPOND TRIPLA WALEU CRISTAL', 103, 'waleu_caixa_correspondencia_tripla_cristal', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3398, 'CAIXA CORRESPOND TRIPLA WALEU FUME', 103, 'waleu_caixa_correspondencia_tripla_fume', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4347, 'CALCULADORA DE BOLSO BRW 8 DIGITOS', 103, 'brw_calculadora_bolso_8_digitos', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2215, 'CALCULADORA GRANDE BRW 12 DIGITOS', 103, 'brw_calculadora_grande_12_digitos', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2214, 'CALCULADORA MEDIA BRW 12 DIGITOS', 103, 'brw_calculadora_media_12_digitos', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3470, 'CALCULADORA PEQUENA BRW 8 DIGITOS', 103, 'brw_calculadora_pequena_8_digitos', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (1276, 'CANETA COMPACTOR 07 AZUL', 103, 'compactor_caneta_07', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2025, 'CARRO FUNC BRALIMPIA AMERICA BOLSA AMA', 102, 'bralimpia_carro_funcional_america', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3512, 'CARRO FUNC BRALIMPIA PAN-AMERICA', 102, 'bralimpia_carro_funcional_pan_america', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (1671, 'CATCHUP AUREA SACHE', 106, 'aurea_ketchup', 'S', 'S', 'N', 'S');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2011, 'CERA LIQUIDA INNOVATION AUDAX 5LT', 102, 'audax_cera_liquida_innovation', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5614, 'CESTO BASC BRALIMPIA 14L PRETO', 102, 'bralimpia_cesto_basculhante_14l', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (1504, 'CESTO BASC BRALIMPIA 23LT AZUL', 102, 'bralimpia_cesto_basculhante_23l_azul', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (1506, 'CESTO BASC BRALIMPIA 23LT VERMELHO', 102, 'bralimpia_cesto_basculhante_23l_vermelho', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3220, 'CESTO GARI 120 C RODA BRALIMPIA VRD CHAM', 102, 'bralimpia_cesto_gari_120l', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2987, 'CESTO GARI 120 C RODA BRALIMPIA VRM CHAM', 102, 'bralimpia_cesto_gari_120l', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5361, 'CESTO GARI 120LT C RODA BRALIMPIA AZUL', 102, 'bralimpia_cesto_gari_120l', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (1903, 'CESTO GARI 120LT C RODA BRALIMPIA BRANCO', 102, 'bralimpia_cesto_gari_120l', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3754, 'CESTO GARI 120LT C RODA BRALIMPIA VERDE', 102, 'bralimpia_cesto_gari_120l', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2026, 'CESTO GARI 120LT C RODA BRALIMPIA VERMEL', 102, 'bralimpia_cesto_gari_120l', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2988, 'CESTO GARI 240 C RODA BRALIMPIA BCO CHAM', 102, 'bralimpia_cesto_gari_240l', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5209, 'CESTO GARI 240LT C RODA BRALIMPIA AZUL', 102, 'bralimpia_cesto_gari_240l', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (1905, 'CESTO GARI 240LT C RODA BRALIMPIA BRANCO', 102, 'bralimpia_cesto_gari_240l', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5758, 'CESTO GARI 240LT C RODA BRALIMPIA CINZA', 102, 'bralimpia_cesto_gari_240l', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5243, 'CESTO GARI 240LT C RODA BRALIMPIA LARANJ', 102, 'bralimpia_cesto_gari_240l', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5244, 'CESTO GARI 240LT C RODA BRALIMPIA MARROM', 102, 'bralimpia_cesto_gari_240l', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3513, 'CESTO GARI 240LT C RODA BRALIMPIA VERDE', 102, 'bralimpia_cesto_gari_240l', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2027, 'CESTO GARI 240LT C RODA BRALIMPIA VERMEL', 102, 'bralimpia_cesto_gari_240l', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2115, 'CLIPS PARA PAPEIS BRW N0', 103, 'brw_clips_para_papeis', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (508, 'CLIPS PARA PAPEIS BRW N2 ', 103, 'brw_clips_para_papeis', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (509, 'CLIPS PARA PAPEIS BRW N3', 103, 'brw_clips_para_papeis', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (1755, 'CLIPS PARA PAPEIS BRW N4', 103, 'brw_clips_para_papeis', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (510, 'CLIPS PARA PAPEIS BRW N6', 103, 'brw_clips_para_papeis', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (1208, 'CLIPS PARA PAPEIS BRW N8', 103, 'brw_clips_para_papeis', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3722, 'COBERTURA CHOCOLATE DU PORTO 1,3KG', 100, 'du_porto_cobertura_1300g', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3728, 'COBERTURA CHOCOLATE DU PORTO 300G', 100, 'du_porto_cobertura_chocolate_300g', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2110, 'COLA BASTAO BRW 21GR', 103, 'brw_cola_bastao_21g', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4968, 'COLA BASTAO BRW 9GR', 103, 'brw_cola_bastao_9g', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5540, 'COLA BRANCA BRW 1KG', 103, 'brw_cola_branca_1kg', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5538, 'COLA BRANCA BRW 40G', 103, 'brw_cola_branca_40g', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5539, 'COLA BRANCA BRW 500G', 103, 'brw_cola_branca_500g', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5659, 'COLA BRANCA BRW 90G', 103, 'brw_cola_branca_90g', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5615, 'COLA COLORIDA BRW 21G C/ 4UN', 103, 'brw_cola_colorida', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5616, 'COLA COM GLITER BRW 25G C/ 6UN', 103, 'brw_cola_com_gliter', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4969, 'COLA EM FITA BRW', 103, 'brw_cola_em_fita', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5179, 'COLA ISOPOR LIQUIDA 80G BRW', 103, 'brw_cola_isopor', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5178, 'COLA SILICONE LIQUIDA 50G BRW', 103, 'brw_cola_silicone', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3226, 'COMBINADO BRALIMPIA COM CABO 25CM', 102, 'bralimpia_combinado_com_cabo', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3970, 'CONJ BALDE TWISTER C PEDAL+MOP BETTANIN', 102, 'bettanin_balde_twister_com_pedal_mop_twister', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2990, 'CONJUNTO BRALIMPIA HIGH TECH 40CM', 102, 'bralimpia_conjunto_high_tech_40cm', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2708, 'COPO BALADA 300ML COPOBRAS MISTO 20X25CX', 101, 'copobras_copo_balada_300ml', 'N', 'S', 'N', 'S');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5658, 'CORRETIVO LIQ BRW 18ML', 103, 'brw_corretivo_liquido', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3960, 'DESENTUPIDOR GRANDE BETTANIN', 102, 'bettanin_desentupidor_grande', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4461, 'DESENTUPIDOR PIAS E RALOS BETTANIN', 102, 'bettanin_desintupidor_pias_ralos', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (140, 'DESINF CLEOSOL AUDAX LAVANDA 5LT', 102, 'audax_desinfetante_cleosol_lavanda', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (138, 'DESINF MAX AUDAX LAVANDA 5LT', 102, 'audax_desinfetante_max_lavanda', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2701, 'DESINFETANTE GOLD FLORAL AUDAX 5LT', 102, 'audax_desinfetante_gold_floral', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (134, 'DET LIQ CLETEX AUDAX 5LT', 102, 'audax_detergente_cletex', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5638, 'DETERGENTE GOLD CLORADO AUDAX 5L', 102, 'audax_detergente_gold_clorado', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2699, 'DETERGENTE GOLD NEUTRO AUDAX 5LT', 102, 'audax_detergente_gold_neutro', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2637, 'DOCE DE LEITE AUREA 4,8 KG', 106, 'aurea_doce_de_leite', 'S', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2466, 'DOCE DE LEITE C/ CHOCOLATE AUREA 4,8KG', 106, 'aurea_doce_de_leite_com_chocolate', 'S', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4163, 'ELASTICO PREMIER 1000GR', 103, 'premier_elastico', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4162, 'ELASTICO PREMIER 500GR ', 103, 'premier_elastico', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4161, 'ELASTICO PREMIER 50GR ', 103, 'premier_elastico', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2367, 'ENCERADEIRA BRALIMPIA MOD.440MM 220V', 102, 'bralimpia_enceradeira_440mm', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (786, 'ESCOVA BETTAJEANS BETTANIN', 102, 'bettanin_escova', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3981, 'ESCOVA BRILHUS MULTIUSO BETTANIN', 102, 'bettanin_escova_brilhus_multiuso', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3959, 'ESCOVA NOVICA ADAPT BETTANIN', 102, 'bettanin_escova_com_cabo', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3983, 'ESCOVA SANITARIA SANILUX C SUP. BETTANIN', 102, 'bettanin_escova_sanitaria_suporte', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4460, 'ESCOVA SANITARIA SANILUX C SUP. BETTANIN', 102, 'bettanin_escova_sanitaria_suporte2', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (762, 'ESCOVA SANITARIA SANILUX S SUP. BETTANIN', 102, 'bettanin_escova_sanitaria_sem_suporte', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2037, 'ESPETO COLETOR DE LIXO (STICHER) BRALIMP', 102, 'bralimpia_espeto_coletor_lixo_sticher', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3976, 'ESPONJA BRILHUS BETTANIN', 102, 'bettanin_esponja_brilhus', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3977, 'ESPONJA ESFREBOM PROTEGE UNHAS BETTANIN', 102, 'bettanin_esponja_esfrebom_protege_unhas', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3760, 'ESTILETE BRW 18MM', 103, 'brw_estilete_18mm', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3759, 'ESTILETE BRW 9MM', 103, 'brw_estilete_9mm', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2216, 'ESTILETE PROF.18MM C/ TRAVA DE SEGUR BRW', 103, 'brw_estilete_18mm_com_trava_seguranca', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4922, 'ESTILETE USO PROF.18MM BRW', 103, 'brw_estilete_18mm_uso_profissional', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3417, 'EXPOSITOR OFFICE BRANCO WALEU', 103, 'waleu_expositor_office', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5364, 'EXTENSAO TELESCOPICA 3M 3 ESTA BRALIMPIA', 102, 'bralimpia_extensao_telescopica', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3868, 'EXTENSAO TELESCOPICA 7,5M BRALIMPIA', 102, 'bralimpia_extensao_telescopica', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2217, 'EXTRATOR DE GRAMPO BRW', 103, 'brw_extratro_grampo', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3468, 'FITA ADES BRW TRANSP 45MMX45M', 103, 'brw_fita_adesiva_45x45', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4348, 'FITA CORRETIVA BRW 5MMX6M', 103, 'brw_fita_corretiva', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5710, 'GAVETEIRO C/ 4 GAVETAS WALEU PRETO', 103, 'waleu_gaveteiro_com_4_gavetas_preto', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4920, 'GRAMPEADOR BRW 25FLS 20CM', 103, 'brw_grampeador_25f_20cm', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2103, 'GRAMPEADOR BRW MET 100 FOLHAS', 103, 'brw_grampeador_metal_100f', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4970, 'GRAMPEADOR BRW MET 240 FOLHAS', 103, 'brw_grampeador_metal_240f', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5541, 'GRAMPEADOR BRW MET MEDIO 25 FOLHAS', 103, 'brw_grampeador_metal_medio_25f', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2102, 'GRAMPEADOR BRW MET PEQUENO', 103, 'brw_grampeador_metal_pequeno', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2218, 'GRAMPEADOR GRANDE BRW', 103, 'brw_grampeador_grande', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2219, 'GRAMPEADOR MEDIO BRW', 103, 'brw_grampeador_medio', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4972, 'GRAMPO GALVANIZADO BRW 23/10', 101, 'brw_grampo_galvanizado_23_10', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (521, 'GRAMPO TRILHO METAL C/50 BRW', 103, 'brw_grampo_trilho_metal', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (1371, 'GRAMPOS BRW COBREADO 26/6', 103, 'brw_grampo_cobreado_26_6', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (1213, 'GRAMPOS BRW GALVANIZADO 26/6', 103, 'brw_grampo_galvanizado_26_6', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (1323, 'GUIA REMOVIVEL BRALIMPIA 25CM', 102, 'bralimpia_guia_removivel', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (824, 'GUIA REMOVIVEL BRALIMPIA 35CM', 102, 'bralimpia_guia_removivel', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (848, 'HASTE C CABO BRALIMPIA TIPO EURO AZUL', 102, 'bralimpia_haste_com_cabo_euro_azul', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (915, 'HIPOCLORITO DE SODIO AUDAX 5LT', 102, 'audax_hipoclorito_de_sodio', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3221, 'KIT BRALIMPIA PLUS COM BOLSA', 102, 'bralimpia_kit_plus_com_bolsa', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4221, 'KIT POTE CRISTALPPOTE 250ML', 101, 'cristalppote_kit_pote_com_tampa_250ml', 'N', 'S', 'N', 'S');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5365, 'KIT PROMOCIONAL 1 AMARELO', 102, 'bralimpia_kit_promocional_1', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4948, 'KIT PROMOCIONAL 2', 102, 'bralimpia_kit_promocional_2', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (1162, 'LAMINA DE BORRACHA BRALIMPIA 35CM', 102, 'bralimpia_laminha_borracha', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2220, 'LAMINA PARA ESTILETE 18MM BRW', 103, 'brw_lamina_para_estilete_18mm', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2221, 'LAMINA PARA ESTILETE 9MM BRW', 103, 'brw_lamina_para_estilete_9mm', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2100, 'LAPIS DE COR BRW', 103, 'brw_lapis_de_cor', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5721, 'LAPIS DE COR ECO SEXTAVADO BRW', 103, 'brw_lapis_de_cor_eco_sextavado', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5181, 'LAPIS PRETO HB REDONDO BRW', 103, 'brw_lapis_preto_hb_redondo', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5543, 'LAPIS VERDE C BORRACHA BRW', 103, 'brw_lapis_verde_com_borracha', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5542, 'LAPIS VERDE HB RECICLADO BRW', 103, 'brw_lapis_verde_hb_reciclado', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5182, 'LAPIS VERDE HB SEXTAVADO BRW', 103, 'brw_lapis_verde_hb_sextavado', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5602, 'LIMPADOR P QUADRO BR BRILLANT COMPACTOR', 103, 'compactor_limpador_quadro_branco_brillant', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2362, 'LIXEIRA 50L ALÇA/TAMPA BRALIMPIA AMARELA', 102, 'bralimpia_lixeira_50l_com_alca', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2363, 'LIXEIRA 50L ALÇA/TAMPA BRALIMPIA AZUL', 102, 'bralimpia_lixeira_50l_com_alca', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2364, 'LIXEIRA 50L ALÇA/TAMPA BRALIMPIA VERDE', 102, 'bralimpia_lixeira_50l_com_alca', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2365, 'LIXEIRA 50L ALÇA/TAMPA BRALIMPIA VERMELH', 102, 'bralimpia_lixeira_50l_com_alca', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5360, 'LIXEIRA P COPOS AZUL BRALIMPIA', 101, 'bralimpia_lixeira_para_copos', 'N', 'N', 'S', 'S');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5668, 'LIXEIRA S GRAV BRALIMPIA 50L AMAREL FERR', 102, 'bralimpia_lixeira_50l_sem_gravuras_com_ferragens', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5669, 'LIXEIRA S GRAV BRALIMPIA 50L AZUL FERRAG', 102, 'bralimpia_lixeira_50l_sem_gravuras_com_ferragens', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (833, 'LT BRALIMPIA EURO AZUL', 102, 'bralimpia_lt_euro_azul', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3978, 'LUVA ESFREBOM FASHION BETTANIN', 102, 'bettanin_luva_fashion', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (1672, 'MAIONESE AUREA SACHE', 106, 'aurea_maionese', 'S', 'S', 'N', 'S');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3338, 'MALETA ARQUIVO PRETA POLYCART C10 PASTAS', 103, 'polycart_maleta_arquivo_com_10_pastas', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2105, 'MARCA TEXTO BRW AMARELO', 103, 'brw_marca_texto_amarelo', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2106, 'MARCA TEXTO BRW AZUL', 103, 'brw_marca_texto_azul', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3663, 'MARCA TEXTO BRW LARANJA', 103, 'brw_marca_texto_laranja', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3662, 'MARCA TEXTO BRW ROSA', 103, 'brw_marca_texto_rosa', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2107, 'MARCA TEXTO BRW VERDE', 103, 'brw_marca_texto_verde', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3469, 'MARCADOR CD DVD BRW PRETO', 103, 'brw_marcador_cd_dvd_preto', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5624, 'MARCADOR PERM COMPACTOR AZUL ABASTECER', 103, 'compactor_marcador_permanente_para_abastecer', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5594, 'MARCADOR QUADRO BRANCO COMPACTOR AZUL', 103, 'compactor_marcador_quadro_branco', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4298, 'MASSA ELASTICA 500G ARCOLOR', 106, 'arcollor_massa_elastica_500g', 'S', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (816, 'MINI KIT BRALIMPIA', 102, 'bralimpia_mini_kit', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2366, 'MODULO P LIXEIRAS 50L C/RODAS BRALIMPIA', 102, 'bralimpia_modulo_lixeira_50l_com_rodas', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5177, 'MOLHA DEDO 12G BRW ', 103, 'brw_molha_dedo_12g', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3961, 'MOP ABRASIVO ESFREBOM BETTANIN', 102, 'bettanin_mop_abrasivo', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3965, 'MOP ESFREGAO ALGODAO ZIG ZAG BETTANIN', 102, 'bettanin_mop_esfregao_algodao', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3966, 'MOP ESFREGAO LIMPATUDO ZIG ZAG BETTANIN', 102, 'bettanin_mop_esfregao_limpatudo', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (767, 'MOP LUSTRADOR ALGODAO ZIG ZAG BETTANIN', 102, 'bettanin_mop_lustrador_algodao', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (1178, 'MOP LUSTRADOR LA BETTANIN', 102, 'bettanin_mop_lustrador_la', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3974, 'MOP NOVICA SPRAY BETTANIN', 102, 'bettanin_mop_spray', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3975, 'MOP NOVICA TORCAO BETTANIN', 102, 'bettanin_mop_torcao', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (765, 'MOP ZIG ZAG SEKITO BETTANIN', 102, 'bettanin_mop_zig_zag_sekito', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (1673, 'MOSTARDA AUREA SACHE', 106, 'aurea_mostarda', 'S', 'S', 'N', 'S');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (1483, 'MULTIUSO AUDAX LAVANDA 500ML', 102, 'audax_multiuso_lavanda_500ml', 'N', 'S', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4997, 'ORGANIZADOR DE CHAVES C/50 WALEU', 103, 'waleu_chaveiro', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3414, 'ORGANIZADOR MOEDAS WALEU CRISTAL', 103, 'waleu_organizador_moedas', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3867, 'PA COLETORA BRALIMPIA SELETIVA AMARELA', 102, 'bralimpia_pa_coletora', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2666, 'PA COLETORA BRALIMPIA SELETIVA AZUL', 102, 'bralimpia_pa_coletora', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2454, 'PA COLETORA BRALIMPIA SELETIVA VERDE', 102, 'bralimpia_pa_coletora', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2999, 'PA COLETORA BRALIMPIA SELETIVA VERMELHA', 102, 'bralimpia_pa_coletora', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3958, 'PA COLETORA NOVIÇA BETTANIN', 102, 'bettanin_pa_coletora', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3238, 'PA COLETORA PLAST PROFISSIONAL BRALIMPIA', 102, 'bralimpia_pa_coletora', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5363, 'PA COLETORA POP BRALIMPIA AZUL CABO ALUM', 102, 'bralimpia_pa_coletora', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (763, 'PA DE ACO NOVICA BETTANIN', 102, 'bettanin_pa', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (1179, 'PA DE CABO LONGO NOVIÇA BETTANIN', 102, 'bettanin_pa_cabo_longo', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3534, 'PALITO DENTE MADEI BILLA EMBALADO 2000UN', 101, 'billa_palito_dente_2000', 'N', 'S', 'N', 'S');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3627, 'PANO MULTIUSO BILLA AZUL 600UN', 102, 'billa_pano_multiuso_azul', 'N', 'N', 'N', 'S');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2619, 'PANO MULTIUSO BILLA LARANJA 600UN', 102, 'billa_pano_multiuso_laranja', 'N', 'N', 'N', 'S');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4880, 'PASTA 12 DIV A4 PLASCONY AZUL', 103, 'plascony_pasta_12div_duplicata', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3834, 'PASTA 12 DIV A4 PLASCONY AZUL SAFIRA', 103, 'plascony_pasta_12div_duplicata', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3833, 'PASTA 12 DIV A4 PLASCONY AZUL TOPAZIO', 103, 'plascony_pasta_12div_duplicata', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3837, 'PASTA 12 DIV A4 PLASCONY FUME', 103, 'plascony_pasta_12div_duplicata', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3836, 'PASTA 12 DIV A4 PLASCONY ROSA TURMALINA', 103, 'plascony_pasta_12div_duplicata', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3835, 'PASTA 12 DIV A4 PLASCONY ROXO AMETISTA', 103, 'plascony_pasta_12div_duplicata', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4881, 'PASTA 12 DIV A4 PLASCONY TRANSPARENTE', 103, 'plascony_pasta_12div_duplicata', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3806, 'PASTA 31 DIV CHEQUE PLASCONY AZUL', 103, 'plascony_pasta_31div_cheque', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3807, 'PASTA 31 DIV CHEQUE PLASCONY FUME', 103, 'plascony_pasta_31div_cheque', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3805, 'PASTA 31 DIV CHEQUE PLASCONY TRANSPARENT', 103, 'plascony_pasta_31div_cheque', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3809, 'PASTA 31 DIV DUPLICATA PLASCONY AZUL', 103, 'plascony_pasta_31div_duplicata', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3808, 'PASTA 31 DIV DUPLICATA PLASCONY FUME', 103, 'plascony_pasta_31div_duplicata', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3810, 'PASTA 31 DIV DUPLICATA PLASCONY TRANSPAR', 103, 'plascony_pasta_31div_duplicata', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3816, 'PASTA 31 DIV OFICIO PLASCONY AZUL', 103, 'plascony_pasta_31div_bicolor', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3815, 'PASTA 31 DIV OFICIO PLASCONY FUME', 103, 'plascony_pasta_31div_bicolor', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3814, 'PASTA 31 DIV OFICIO PLASCONY TRANSPARENT', 103, 'plascony_pasta_31div_bicolor', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3780, 'PASTA ABA 30 PLASCONY AMARELA', 103, 'plascony_pasta_aba_30', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3778, 'PASTA ABA 30 PLASCONY AZUL', 103, 'plascony_pasta_aba_30', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3776, 'PASTA ABA 30 PLASCONY FUME', 103, 'plascony_pasta_aba_30', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3781, 'PASTA ABA 30 PLASCONY LILAS', 103, 'plascony_pasta_aba_30', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3758, 'PASTA ABA 30 PLASCONY ROSA', 103, 'plascony_pasta_aba_30', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3777, 'PASTA ABA 30 PLASCONY TRANSPARENTE', 103, 'plascony_pasta_aba_30', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3779, 'PASTA ABA 30 PLASCONY VERDE', 103, 'plascony_pasta_aba_30', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3757, 'PASTA ABA 30 PLASCONY VERMELHA', 103, 'plascony_pasta_aba_30', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4300, 'PASTA AMERICANA AVELA 800G ARCOLOR', 106, 'arcollor_pasta_americana_800g', 'S', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5175, 'PASTA AZ A4 LOMBO LARGO BRW CINZA', 103, 'brw_pasta_az_cinza', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3839, 'PASTA CATALOGO A4 PLASCONY AZUL', 103, 'plascony_pasta_catalogo', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3840, 'PASTA CATALOGO A4 PLASCONY FUME', 103, 'plascony_pasta_catalogo', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3838, 'PASTA CATALOGO A4 PLASCONY TRANSPARENTE', 103, 'plascony_pasta_catalogo', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5519, 'PASTA CATALOGO OFICIO PLASCONY FUME', 103, 'plascony_pasta_catalogo', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5520, 'PASTA CATALOGO OFICIO PLASCONY TRANSP', 103, 'plascony_pasta_catalogo', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3797, 'PASTA TRILHO OF PLASCONY AMARELA', 103, 'plascony_pasta_trilho', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3798, 'PASTA TRILHO OF PLASCONY AZUL', 103, 'plascony_pasta_trilho', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3802, 'PASTA TRILHO OF PLASCONY FUME', 103, 'plascony_pasta_trilho', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3804, 'PASTA TRILHO OF PLASCONY LILAS', 103, 'plascony_pasta_trilho', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3799, 'PASTA TRILHO OF PLASCONY ROSA', 103, 'plascony_pasta_trilho', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3803, 'PASTA TRILHO OF PLASCONY TRANSPARENTE', 103, 'plascony_pasta_trilho', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3800, 'PASTA TRILHO OF PLASCONY VERDE', 103, 'plascony_pasta_trilho', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3801, 'PASTA TRILHO OF PLASCONY VERMELHA', 103, 'plascony_pasta_trilho', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5625, 'PASTAMIX 800G', 106, 'mix_pastamix_800g', 'S', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (1887, 'PERCEVEJO LATONADO BRW N2 ', 103, 'brw_percevejo_latonado_n2', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3942, 'PERFURADOR GRANDE BRW', 103, 'brw_perfurador_grande', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3941, 'PERFURADOR MEDIO BRW', 103, 'brw_perfurador_medio', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3761, 'PISTOLA COLA QUENTE BRW GRANDE', 103, 'brw_pistola_cola_quente_grande', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3762, 'PISTOLA COLA QUENTE BRW PEQUENA', 103, 'brw_pistola_cola_quente_pequena', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (818, 'PLACA SINAL BRAL PISO MOLHADO', 102, 'bralimpia_placa_sinal_piso_molhado', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3875, 'PO PARA GELADOS BLUE DU PORTO 1KG', 100, 'du_porto_po_para_gelados_1kg', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3893, 'PO PARA GELADOS BRIGADEIRO DU PORTO 1KG', 100, 'du_porto_po_para_gelados_1kg', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3735, 'PO PARA GELADOS COCO DU PORTO 1KG', 100, 'du_porto_po_para_gelados_1kg', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3892, 'PO PARA GELADOS CREME DU PORTO 1KG', 100, 'du_porto_po_para_gelados_1kg', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3736, 'PO PARA GELADOS GRAVIOLA DU PORTO 1KG', 100, 'du_porto_po_para_gelados_1kg', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3737, 'PO PARA GELADOS LEITE COND DU PORTO 1KG', 100, 'du_porto_po_para_gelados_1kg', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3734, 'PO PARA GELADOS LIMAO DU PORTO 1KG', 100, 'du_porto_po_para_gelados_1kg', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3738, 'PO PARA GELADOS MORANGO DU PORTO 1KG', 100, 'du_porto_po_para_gelados_1kg', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3876, 'PO PARA GELADOS NATA DU PORTO 1KG', 100, 'du_porto_po_para_gelados_1kg', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3872, 'PO PARA GELADOS UVA DU PORTO 1KG', 100, 'du_porto_po_para_gelados_1kg', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3404, 'PORTA CANETAS/CLIPS/LEMBR WALEU CRISTAL', 103, 'waleu_porta_caneta_clips_lembrete_cristal', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3405, 'PORTA CANETAS/CLIPS/LEMBR WALEU FUME', 103, 'waleu_porta_caneta_clips_lembrete_fume', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3528, 'PORTA CANUDOS METAL AURIMAR BRANCO', 101, 'aurimar_porta_canudo_metal_branco', 'N', 'N', 'N', 'S');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5713, 'PRANCHETA SUPER WALEU CRISTAL', 103, 'waleu_prancheta_super_cristal', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (278, 'PROTETOR DE ALUMINIO FOGAO TERMICA', 101, 'termica_protetor_fogao', 'N', 'S', 'N', 'S');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (828, 'PULVERIZADOR BRALIMPIA 1L', 102, 'bralimpia_pulverizador_500ml_1l', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (1260, 'PULVERIZADOR BRALIMPIA 500ML', 102, 'bralimpia_pulverizador_500ml_1l', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (849, 'RASPADOR PESADO BRALIMPIA COM CABO', 102, 'bralimpia_raspador_pesado_com_cabo', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (1159, 'RASPADOR PESADO C CABO BRALIMPIA', 102, 'bralimpia_raspador_pesado_com_cabo', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3964, 'REFIL MOP ABRASIVO ESFREBOM BETTANIN', 102, 'bettanin_refil_abrasivo', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3973, 'REFIL MOP BALDE TWISTER C/PEDAL BETTANIN', 102, 'bettanin_refil_mop_twister', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3535, 'REFIL MOP BRALIMPIA CRU LOOP CINTA VERME', 102, 'bralimpia_refil_mop_cru_loop_cinta_vermelho', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (843, 'REFIL MOP BRALIMPIA MICROFIBRA BCO', 102, 'bralimpia_refil_mop_microfibra_branco', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3967, 'REFIL MOP ESFREGAO ALGODAO ZIG BETTANIN', 102, 'bettanin_refil_algodao', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3968, 'REFIL MOP ESFREGAO LIMPATUDO BETTANIN', 102, 'bettanin_refil_limpatudo', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3963, 'REFIL MOP LUSTRADOR ALGODAO ZIG BETTANIN', 102, 'bettanin_refil_lustrador_algodao', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3962, 'REFIL MOP LUSTRADOR LA BETTANIN', 102, 'bettanin_refil_lustrador_la', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3969, 'REFIL MOP ZIG ZAG SEKITO BETTANIN', 102, 'bettanin_refil_zig_zag_sekito', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (819, 'REFIL MOPINHO BRALIMPIA  30CM', 102, 'bralimpia_refil_mopinho_30cm', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (817, 'RODO PLASTICO BRALIMPIA AZUL 55CM', 102, 'bralimpia_rodo_plastico_55cm', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (845, 'RODO PLASTICO BRALIMPIA AZUL DRY 45CM', 102, 'bralimpia_rodo_plastico_dry_azul', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (846, 'RODO PLASTICO BRALIMPIA AZUL DRY 55CM', 102, 'bralimpia_rodo_plastico_dry_azul', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (844, 'RODO PLASTICO BRALIMPIA AZUL DRY 65CM', 102, 'bralimpia_rodo_plastico_dry_azul', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3957, 'RODO VAI E VEM M BETTANIN', 102, 'bettanin_rodo_vai_vem_m', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (785, 'RODO VAI E VEM P BETTANIN', 102, 'bettanin_rodo_vai_vem_p', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (4520, 'SABONETE ESP AUDAX ALLCLEAN ERVA DOCE 5L', 102, 'audax_sabonete_espuma_all_clean', 'N', 'N', 'S', 'S');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (151, 'SABONETE LIQ AUDAX ALL CLEAN ANTISEP 5LT', 102, 'audax_sabonete_antisseptico_all_clean', 'N', 'N', 'S', 'S');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (1628, 'SABONETE LIQ DESENGRAXANTE AUDAX 5LT', 102, 'audax_sabonete_desengraxante_5l', 'N', 'N', 'S', 'S');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2989, 'SABONETEIRA DE RESERVATORIO BRALIMPIA', 102, 'bralimpia_saboneteira_reservatorio', 'N', 'N', 'S', 'S');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3612, 'SACO COM 11 FUROS A4 BRW', 103, 'brw_saco_com_11_furos_a4', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2993, 'SUPER MOP DOMESTICO BRALIMPIA', 102, 'bralimpia_super_mop_domestico', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5172, 'SUPORTE  FITA ADESIVA GRANDE BRW AZUL', 103, 'brw_suporte_fita_adesiva_grande', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5173, 'SUPORTE  FITA ADESIVA MEDIO BRW AZUL', 103, 'brw_suporte_fita_adesiva_medio', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (1907, 'TELA MICTORIO AZUL BRALIMPIA', 102, 'bralimpia_tela_mictorio_azul_verde', 'N', 'N', 'S', 'S');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (1909, 'TELA MICTORIO VERMELHA BRALIMPIA', 102, 'bralimpia_tela_mictorio_vermelha_amarela', 'N', 'N', 'S', 'S');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5176, 'TESOURA 17CM BLISTER BRW', 103, 'brw_tesoura_17cm_blister', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5353, 'TESOURA 21CM BLISTER BRW', 103, 'brw_tesoura_21cm_blister', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2222, 'TESOURA ESCOLAR 13CM BRW', 103, 'brw_tesoura_escolar_13cm', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (5592, 'TINTA P MARCADOR PERM COMPACTOR AZUL', 103, 'compactor_tinta_marcador_permanente', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3979, 'VASSOURA BRILHUS BETTANIN', 102, 'bettanin_vassoura_brilhus', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3947, 'VASSOURA MACIA 40CM BRALIMPIA', 102, 'bralimpia_vassoura_macia', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (2038, 'VASSOURA MINI PARA PA COLETORA BRALIMPIA', 102, 'bralimpia_vassoura_mini_pa_coletora', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3954, 'VASSOURA ORIGINAL BETTANIN', 102, 'bettanin_vassoura_original', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (783, 'VASSOURA PISO DELICADO BETTANIN', 102, 'bettanin_vassoura_piso_delicado', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (784, 'VASSOURA VARRY 1000 BETTANIN', 102, 'bettanin_vassoura_varry', 'N', 'N', 'N', 'N');\n ");
        stringBuilder.append("INSERT INTO PRODUTOS (CODIGO, DESCRICAO, DEPARTAMENTO, CAMINHO, PADARIA, MERCADINHO, RESTAURANTE, CLINICAS) VALUES (3982, 'VASSOURITA BRILHUS BETTANIN', 102, 'bettanin_vassourita_brilhus', 'N', 'N', 'N', 'N'); ");


        return stringBuilder.toString();
    }

    public static int[] gerarPapelaria(){

        int[] papelaria = new int[]{
                R.drawable.brw_corretivo_em_fita};

        return papelaria;
    }

    public static int[] gerarLimpeza(){

        int[] limpeza = new int[]{
                R.drawable.audax_base_seladora_innovation,
                R.drawable.audax_cera_liquida_innovation,
                R.drawable.audax_desinfetante_cleosol_lavanda,
                R.drawable.audax_desinfetante_gold_floral,
                R.drawable.audax_desinfetante_max_lavanda,
                R.drawable.audax_detergente_cletex,
                R.drawable.audax_detergente_gold_clorado,
                R.drawable.audax_detergente_gold_neutro,
                R.drawable.audax_hipoclorito_de_sodio,
                R.drawable.audax_multiuso_lavanda_500ml,
                R.drawable.audax_sabonete_antisseptico_all_clean,
                R.drawable.audax_sabonete_desengraxante_5l,
                R.drawable.audax_sabonete_espuma_all_clean,
                R.drawable.betanin_mop_zig_zag_sekito,
                R.drawable.bettanin_balde_10l_sekito,
                R.drawable.bettanin_balde_14l_zig_zag,
                R.drawable.bettanin_balde_twister_com_pedal_mop_twister,
                R.drawable.bettanin_combo,
                R.drawable.bettanin_desentupidor_grande,
                R.drawable.bettanin_desintupidor_pias_ralos,
                R.drawable.bettanin_escova,
                R.drawable.bettanin_escova_brilhus_multiuso,
                R.drawable.bettanin_escova_com_cabo,
                R.drawable.bettanin_escova_sanitaria_sem_suporte,
                R.drawable.bettanin_escova_sanitaria_suporte,
                R.drawable.bettanin_escova_sanitaria_suporte2,
                R.drawable.bettanin_esponja_brilhus,
                R.drawable.bettanin_esponja_esfrebom_protege_unhas,
                R.drawable.bettanin_luva_fashion,
                R.drawable.bettanin_mop_abrasivo,
                R.drawable.bettanin_mop_esfregao_algodao,
                R.drawable.bettanin_mop_esfregao_limpatudo,
                R.drawable.bettanin_mop_lustrador_algodao,
                R.drawable.bettanin_mop_lustrador_la,
                R.drawable.bettanin_mop_spray,
                R.drawable.bettanin_mop_torcao,
                R.drawable.bettanin_pa,
                R.drawable.bettanin_pa_cabo_longo,
                R.drawable.bettanin_pa_coletora,
                R.drawable.bettanin_refil_abrasivo,
                R.drawable.bettanin_refil_algodao,
                R.drawable.bettanin_refil_limpatudo,
                R.drawable.bettanin_refil_lustrador_algodao,
                R.drawable.bettanin_refil_lustrador_la,
                R.drawable.bettanin_refil_mop_twister,
                R.drawable.bettanin_refil_zig_zag_sekito,
                R.drawable.bettanin_rodo_vai_vem_m,
                R.drawable.bettanin_rodo_vai_vem_p,
                R.drawable.bettanin_vassoura_brilhus,
                R.drawable.bettanin_vassoura_original,
                R.drawable.bettanin_vassoura_piso_delicado,
                R.drawable.bettanin_vassoura_varry,
                R.drawable.bettanin_vassourita_brilhus,
                R.drawable.billa_palito_dente_2000,
                R.drawable.billa_pano_multiuso_azul,
                R.drawable.billa_pano_multiuso_laranja,
                R.drawable.bralimpia_armacao_plus,
                R.drawable.bralimpia_balde_4l_com_alca,
                R.drawable.bralimpia_balde_espremedor_doblo,
                R.drawable.bralimpia_balde_espremedor_mopinho,
                R.drawable.bralimpia_cabo_fosco,
                R.drawable.bralimpia_carro_funcional_america,
                R.drawable.bralimpia_carro_funcional_pan_america,
                R.drawable.bralimpia_cesto_basculhante_14l,
                R.drawable.bralimpia_cesto_basculhante_23l_azul,
                R.drawable.bralimpia_cesto_basculhante_23l_verde,
                R.drawable.bralimpia_cesto_basculhante_23l_vermelho,
                R.drawable.bralimpia_cesto_gari_120l,
                R.drawable.bralimpia_cesto_gari_240l,
                R.drawable.bralimpia_combinado_com_cabo,
                R.drawable.bralimpia_conjunto_high_tech_40cm,
                R.drawable.bralimpia_enceradeira_440mm,
                R.drawable.bralimpia_escada_aluminio,
                //R.drawable.bralimpia_espeto_coletor_lixo_sticher,
                R.drawable.bralimpia_extensao_telescopica,
                R.drawable.bralimpia_guia_removivel,
                R.drawable.bralimpia_haste_com_cabo_euro_azul,
                R.drawable.bralimpia_kit_plus_com_bolsa,
                R.drawable.bralimpia_kit_promocional_1,
                R.drawable.bralimpia_kit_promocional_2,
                R.drawable.bralimpia_laminha_borracha,
                R.drawable.bralimpia_lixeira_50l_com_alca,
                R.drawable.bralimpia_lixeira_50l_sem_gravuras_com_ferragens,
                R.drawable.bralimpia_lixeira_para_copos,
                R.drawable.bralimpia_lt_euro_azul,
                R.drawable.bralimpia_mini_kit,
                R.drawable.bralimpia_modulo_lixeira_50l_com_rodas,
                R.drawable.bralimpia_pa_coletora,
                R.drawable.bralimpia_placa_sinal_piso_molhado,
                R.drawable.bralimpia_pulverizador_500ml_1l,
                R.drawable.bralimpia_raspador_pesado_com_cabo,
                R.drawable.bralimpia_refil_mop_cru_loop_cinta_vermelho,
                R.drawable.bralimpia_refil_mop_microfibra_branco,
                R.drawable.bralimpia_refil_mopinho_30cm,
                R.drawable.bralimpia_rodo_plastico_55cm,
                //R.drawable.bralimpia_rodo_plastico_dry_azul,
                R.drawable.bralimpia_saboneteira_reservatorio,
                R.drawable.bralimpia_super_mop_domestico,
                R.drawable.bralimpia_tela_mictorio_azul_verde,
                R.drawable.bralimpia_tela_mictorio_vermelha_amarela,
                R.drawable.bralimpia_vassoura_macia,
                R.drawable.bralimpia_vassoura_mini_pa_coletora,
                R.drawable.brlimpia_armacao_profissional
        };

        return limpeza;
    }

    public static int[] gerarDescartaveis(){

        int[] descartaveis = new int[]{
                R.drawable.copobras_copo_balada_300ml,
                R.drawable.cristalppote_kit_pote_com_tampa_250ml,
                R.drawable.termica_protetor_fogao};

        return descartaveis;
    }

    public static int[] gerarConfeitaria(){

        int[] confeitaria = new int[]{
                R.drawable.arcollor_massa_elastica_500g,
                R.drawable.arcollor_pasta_americana_800g,
                R.drawable.aurea_doce_de_leite,
                R.drawable.aurea_doce_de_leite_com_chocolate,
                R.drawable.mix_pastamix_800g};

        return confeitaria;
    }

    public static int[] gerarSorveteria(){

        int[] sorveteria = new int[]{
                R.drawable.du_porto_cobertura_1300g,
                R.drawable.du_porto_cobertura_chocolate_300g,
                R.drawable.du_porto_po_para_gelados_1kg};

        return sorveteria;
    }

    public static String inserirFotoBanco(int codigo, String descricao, int departamento, String caminho, String padaria, String mercadinho, String restaurante, String clinica){
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append("INSERT INTO PRODUTOS ( ");
        stringBuilder.append("CODIGO, ");
        stringBuilder.append("DESCRICAO, ");
        stringBuilder.append("DEPARTAMENTO, ")
        stringBuilder.append("CAMINHO, ");
        stringBuilder.append("PADARIA, ");
        stringBuilder.append("MERCADINHO, ");
        stringBuilder.append("RESTAURANTE, ");
        stringBuilder.append("CLINICAS) ");
        stringBuilder.append("VALUES ( ");
        stringBuilder.append(codigo + ", ");
        stringBuilder.append(descricao + ", ");
        stringBuilder.append(departamento + ", ");
        stringBuilder.append(caminho + ", ");
        stringBuilder.append(padaria + ", ");
        stringBuilder.append(mercadinho + ", ");
        stringBuilder.append(restaurante + ", ");
        stringBuilder.append(clinica + ") ; ");

        return stringBuilder.toString();    
    }
}
